### ISSUE TITLE
Printing maps does not work

### ISSUE THREAD

**Issue by gmolinario** [GFDRR/geonode-afghanistan#7]
Tested on a few different maps, the printing button does not trigger any action

**Comment by afabiani** [comment]
Confirmed, it looks like related to an issue already fixed on GeoNode 2.10.x

The "proxy" was not able to recognize the GeoServer endpoints exposed through HTTPS protocol.

References #9

**Comment by afabiani** [comment]
This should be fixed now, with the upgrade to GeoNode 2.10.1

**Comment by simboss** [comment]
We tested the configuration we created with some of the configured maps.

[Here](https://github.com/GFDRR/geonode-afghanistan/files/3658953/download.pdf) is an example.

Notice that we might want to tweak over time the configuration (printing layouts, memory for the  print, and so on) accord to how the configured data and layers will evolve.

**Comment by gmolinario** [comment]
hi @simboss I still get an error - is this issue resolved? thank you 
![Screenshot 2019-10-03 23 47 02](https://user-images.githubusercontent.com/37064958/66166729-66dfa280-e638-11e9-9bd2-c3f39167638f.png)

**Comment by cgiovando** [comment]
Hi @simboss - I tried the print functions on a few different maps, and found out that the issue only happens with some layers, and when the print preview if showing _empty_ or _solid color fill_:

![Screen Shot 2019-10-04 at 09 08 21](https://user-images.githubusercontent.com/10201533/66188164-e5633100-e686-11e9-8420-997f0fa9eaa2.jpg)

`Error on printing: <html> <head><title>502 Bad Gateway</title></head> <body bgcolor="white"> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.10.3 (Ubuntu)</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

This other map I just created seems to be printing fine:

![Screen Shot 2019-10-04 at 09 05 43](https://user-images.githubusercontent.com/10201533/66188187-f57b1080-e686-11e9-94c7-4172ca39980b.jpg)

I haven't found a specific pattern. Can you please check and fix? Thanks!

**Comment by simboss** [comment]
@cgiovando @gmolinario can you indicated at least one map that does not work for you?

I just tested 4 or 5 of them and they all printed for me.

**Comment by simboss** [comment]
Just tried https://disasterrisk.af/maps/1948/view and it worked for me...

**Comment by simboss** [comment]
Let's keep this open for the moment, as we were not able to replicate.

@gmolinario can you try again and indicate the URL of the map that does not work for you.

**Comment by gmolinario** [comment]
@simboss @cgiovando I tested a few as well and it seems like it's all working. If @cgiovando doesn't have anything to add here we can close this one?

**Comment by simboss** [comment]
I have something minor. By default we print in A3 which is too much imho and uses a ton of memory.
I will ask Alessio if we can change the order or remove A3 alltogether.

**Comment by afabiani** [comment]
@simboss A3 layout has been removed.
